name: laundry_mate
description: A Flutter application for laundry services

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1  # State management
  image_picker: ^1.0.4  # For picking images from gallery/camera
  font_awesome_flutter: ^10.4.0
  flutter_staggered_animations: ^1.0.0
  # OpenStreetMap dependencies
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^9.0.2
  # For HTTP requests
  http: ^1.5.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.1
  # Icons package
  iconsax: ^0.0.8




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add the following assets section
  assets:
    - assets/images/laundry_background.png
    - assets/images/laundry_background 1.jpg
    - assets/images/background_city_view.jpg
    - assets/images/city_img.jpg
    - assets/images/
    - assets/images/shop 1.jpg
    - assets/images/shop 2.jpg
    - assets/images/shop 3.jpg
    - assets/images/shop 4.jpg
    - assets/images/shop 5.jpg
    - assets/images/shop 6.jpg
    # Or include the whole images directory:
    # - assets/images/


  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
